### ISSUE TITLE
Integrate CMake file

### ISSUE THREAD

**Issue by aregtech** [aregtech/areg-sdk#28]
Similar to Makefile, there should be integrate CMake 
- to compile all project
- generate files in `product/gen` folder
- Add possibility to include `.siml` files in CMake automatically to generate sources.

**Comment by Ali-Nasrolahi** [comment]
Hi. May I get assigned this issue?

**Comment by aregtech** [comment]
@Ali-Nasrolahi, I've assigned the ticket to you. 

As a hint / help, please see the scripts of Makefile and [this](https://github.com/aregtech/areg-sdk/blob/master/docs/HOWTO.md#make) description. Important:
1. Use `areg-sdk/conf/` folder to set there **common** and **user specific** settings. You can create new `cmake` folder for that.
2. All outputs should be in `areg-sdk/product` folder, which is created when compile.

**Comment by Ali-Nasrolahi** [comment]
Thanks. @aregtech

**Comment by aregtech** [comment]
Hi @Ali-Nasrolahi 
I hope you are doing well.
Just wanted to ask about the progress to complete this issue. I'm going to prepare next release where the Cmake will be one of important progress :) Would be great to if you could complete this issue in the next 2-3 weeks.

**Comment by Ali-Nasrolahi** [comment]
Hello @aregtech,
Thank you, hope you are doing well, too.
Well, fortunately project has been going well and hopefully the 2-3 weeks deadline would be more than enough.
So you could count on it pretty well.

In the meantime, please let me know if anything comes up with project which needs to be considered. :)

Thanks.

**Comment by aregtech** [comment]
I'm happy to hear that 2-3 weeks are fine, @Ali-Nasrolahi 
Actually, in this project there are still many things to do 😀
In the near future i'm going to integrate [googletest](https://github.com/google/googletest) (integration via CMake). I didn't decide yet whether this will integrate in upcoming or next release. If you are interested, we can discuss details later, after you complete CMake integration. 
Have a great start of week!

**Comment by Ali-Nasrolahi** [comment]
Great, we could discuss more about it in near future then.
Have a great week ahead :)

**Comment by aregtech** [comment]
This ticket can be closed. If something is wrong, we can open a bug ticket.
Thank you @Ali-Nasrolahi for the implementation and @biwiki for helping to review. 
I appreciate very much your cooperation.
