### ISSUE TITLE
Access mcrouter and logger services from WSL

### ISSUE THREAD

**Issue by aregtech** [aregtech/areg-sdk#336]
**Description:**  
The `mcrouter` and `logcollector` services are designed to run on both Windows and Linux platforms. However, when these services are running on Windows, applications running in WSL (Windows Subsystem for Linux) with the Ubuntu distribution fail to connect to `mcrouter` and `logcollector`. The reverse scenario works correctly: services running in WSL can be accessed by applications on Windows.  

**Steps to Reproduce:**  
1. Compile AREG SDK under **Windows** with logging enabled (default behavior).  
2. Start `mcrouter.exe` and `logcollector.exe` on Windows.  
3. (Optional) Verify the connection on Windows:  
    - Start `logobserver.exe`.  
    - Type `-r` to start the observer and `-i` to list connected instances.  
    - **Result:** `mcrouter.exe` is listed as connected.  
4. Open **WSL** and compile AREG SDK under Linux (Ubuntu) with logging enabled.  
5. Start `logobserver.elf` in WSL. Attempt to connect to the `logcollector.exe` running on Windows:  
    - Type `-r` to start the observer and `-i` to list connected instances.  
    - **Result:** The observer displays a message stating that no instance is connected.  
6. Start an IPC-enabled application (e.g., the client service application from Example 12):  
    - **Result:** The application fails to communicate with `mcrouter` and `logcollector`.  

**Expected Behavior:**  
Applications running in WSL (Ubuntu) should successfully connect to `mcrouter` and `logcollector` services running on Windows, similar to how Windows applications can connect to services running in WSL.  

**Observed Workarounds Attempted:**  
1. Changed the IP address of `mcrouter` and `logcollector` from `127.0.0.1` to a host IP address (`172.23.96.1` obtained via `ipconfig`).  
2. Modified the Windows Defender Firewall settings to allow connections.  
   - The firewall changes did not resolve the issue, but it is unclear if the settings were configured correctly.  

**Environment:**  
- **Operating System:** Windows 10/11 with WSL (Ubuntu Linux distro)  
- **Architecture:** x64  
- **Compiler:**  
  - Windows: MSVC (`cl`)  
  - Linux (WSL): g++ or clang++  
- **AREG SDK Version:** Latest repository version  

**Additional Context:**  
This issue appears to be related to network configuration or security settings rather than a bug in the AREG SDK. There is a known challenge with accessing Windows services from WSL, but no straightforward solution has been found so far.  

**IP Configuration for `mcrouter` and `logcollector`:**  
- To change the `mcrouter` IP address:  
  Edit the line `router::*::address::tcpip = 127.0.0.1` in the [areg.init file](https://github.com/aregtech/areg-sdk/blob/aa8f967ccfb546ade808c6ca82583630f0bf2e82/framework/areg/resources/areg.init#L180). Replace `127.0.0.1` with the desired IP (e.g., host IP from `ipconfig`).  
- To change the `logcollector` IP address:  
  Edit the line `logger::*::address::tcpip = 127.0.0.1` in the [areg.init file](https://github.com/aregtech/areg-sdk/blob/master/framework/areg/resources/areg.init#L189). Replace `127.0.0.1` with the desired IP.

**Comment by amesserla** [comment]
It looks like the issue is mcrouter.exe and logcollector.exe are listening on the localhost (127.0.0.1) IP address, which  WSL doesn't seem to be able to access with the NAT networking mode setting. (I tested this by hosting an http server on Windows and trying to use `curl` to access it from WSL, which failed when the server was hosted on 127.0.0.1. Changing the hosting IP address to 0.0.0.0 allowed me to use curl to access the server from WSL. I did have to make a firewall rule to allow this connection). 

One option might be to change which IP address the Windows executables are listening on, and then changing the WSL IP address settings to the IP address of the Windows machine as seen from WSL. I tried making the change `router::*::address::tcpip = 0.0.0.0` in the Windows areg.init file, but mcrouter still listened on 127.0.0.1.  

Alternatively, the "Mirrored" network setting in WSL is supposed to let WSL access localhost, but I wasn't able to test this on my machine.

**Comment by aregtech** [comment]
Hi @amesserla ,
thank you very much for detailed analyzes. I would be very happy if you help to resolve this issue. A detailed description to solve the problem would be highly appreciated.

You wrote:
>  I tried making the change router::*::address::tcpip = 0.0.0.0 in the Windows areg.init file, but mcrouter still listened on 127.0.0.1.

hmmm... I'll debug this to analyze why it is not accepting new IP-address and let you know. Very probable that it is a bug on my side -- filtered `0.0.0.0` IP. But before that, please check the content of `areg.init` configuration file before running binary:
1. If you make any changed in the `<buidl-binaries>/bin/config/areg.init` file and make a build, it will overwrite the file.
2. Alternatively, if it is annoying to change the IP-address after each build, you can copy and rename the `areg.init` file and start `mcrouter` or `logcollector` from command line with the option `--config`. For example:
   ```bash
   mcrouter --config=./config/mcrouter.init
   ```

P.S. Please note, that I have changed the name of log collector executable. Before it was `logger`, now it is `logcollector`. I'll make appropriate updates in the description.

**Comment by aregtech** [comment]
@amesserla , as I was expecting, there was a bug in the code. The fix will be shortly in the main branch

**Comment by aregtech** [comment]
done. 
@amesserla, can you please test again the case of setting `0.0.0.0`?

**Comment by amesserla** [comment]
This fixed the issue for mcrouter. I found the same bug around line 422 (clientSocketConnect) of [NESocket.cpp](https://github.com/aregtech/areg-sdk/blob/master/framework/areg/base/private/NESocket.cpp) which currently reads 
`   const char * host = hostName.empty() ? hostName.data() : NESocket::LocalHost.data()`

After making the same change as you did for serverSocketConnect (`hostname.empty() == false`) and rebuilding, I was able to get the logobserver on WSL to connect to the mcrouter and logcollector on Windows.

**Comment by aregtech** [comment]
@amesserla ,

ah... you are absolutely right!

I've made changes and tested by mixing executables in different platforms `mcrouter.exe`, `logcollector.elf`, `logobserver.exe`, and example applications `12_pubclient.exe` and `12_pubservice.elf`. Worked perfectly.
Thank you very much finding bug and helping to resolve!

**Comment by aregtech** [comment]
**Bug Fix Description:**  
The issue was caused by the IP address specified in the `areg.init` file being ignored. Instead, the system was always defaulting to `localhost`. Due to a known limitation where WSL (Windows Subsystem for Linux) and Windows cannot communicate via `localhost`, processes running on different platforms were unable to exchange messages.  

### Solution:  
The bug was fixed to ensure that the IP address set in the `areg.init` file is correctly applied.  

### Verification Steps:  
The fix was tested in the following scenario:  
1. **Windows:** `mcrouter.exe`, `logobserver.exe`, and `12_pubclient.exe` were executed.  
2. **WSL (Ubuntu):** `logobserver.elf` and `12_pubservice.elf` were executed.  

### Configuration Changes in `areg.init`:  
The following IP addresses were set for the test:  
```plaintext
router::*::address::tcpip   = 192.168.178.45   # Windows IP address  
logger::*::address::tcpip   = 192.168.178.50   # WSL IP address  
```  

### Test Results:  
The tests were successful, and communication between processes running on Windows and WSL worked seamlessly without any issues.
