### ISSUE TITLE
Integrate google test in CMake

### ISSUE THREAD

**Issue by aregtech** [aregtech/areg-sdk#60]
**Goal**
Integrate [Google test](https://github.com/google/googletest) in the AREG SDK to star developing unit tests.

**Motivation**
The unit tests are used to test small functions / functionalities and it is an effective tool to find and fix bugs. Applications having high rate of unit test code coverage are quite stable. Our minimum goal is to have high rate of code coverage of `base` module, which contains collection of bases objects.

**Background information**
AREG SDK is possible to compile via `cmake`. The GTest contains well description how to integrate it in the project via `CMakeLists.txt`. In addition, there are very many projects that can be an example of integrating GTest.

**Comment by Reenotar** [comment]
Hi, when do you think the CMake integration will be completed? :)

**Comment by aregtech** [comment]
Hi @Stefan-TU, 
difficult to say. The sooner it is finished, the sooner can start writing unit tests. But is not something that burns :) 
How long you think it may take? :)

**Comment by Reenotar** [comment]
Good question :D just curious, because [Issue#28](https://github.com/aregtech/areg-sdk/issues/28) is still open, so I assume that it isn't complete or it is waiting for approval of some kind. Also, I am new to github, but I was interested in trying integrating google tests (so, about how long it would take, I don't know, hope it wouldn't take more than 3-4 weeks)

**Comment by aregtech** [comment]
Hi @Stefan-TU, the Issue #28 is nearly completed :) 
The changes are in the branch [20220205-issue18-cmake](https://github.com/aregtech/areg-sdk/tree/20220205-issue18-cmake). So that I was expecting integration of GTest in less than 3 weeks. If you are interested, i can assign this issue to you and you can try. Maybe I'm wrong and indeed it is a work for a few weeks :)
All latest changes are in the [20220701-candidate](https://github.com/aregtech/areg-sdk/tree/20220701-candidate), which is currently broken and I'll fix within next couple of days. After all changes I'll merge them to master. Maybe after integrating GTest.

**Comment by Reenotar** [comment]
@aregtech so, to [branch](https://github.com/aregtech/areg-sdk/tree/20220205-issue18-cmake) I could integrate GTests?

**Comment by aregtech** [comment]
@Stefan-TU, right :)

**Comment by Reenotar** [comment]
@aregtech okay, assign this to me, I'll do my best :)

**Comment by aregtech** [comment]
Thank you!
Meanwhile, if you need more details in CMake or find any issue, please communicate with @Ali-Nasrolahi
He is the master of cmake and made great job :)

**Comment by aregtech** [comment]
Hi @Stefan-TU 
In case if you already work on this issue, we've just made some important changes in the [20220701-candidate](https://github.com/aregtech/areg-sdk/tree/20220701-candidate) branch, which include changes in CMakeFiles. Please update your sources. From this point, it is the branch with all latest changes.
Thank you and have fun! :)

**Comment by aregtech** [comment]
The branch `20220701-candidate` is integrated in the `master`.

@Stefan-TU , can you please inform whether you still have interest to work in this issue?

**Comment by harshit496** [comment]
@aregtech I would like to contribute to this issue. Could you assign this to me?

**Comment by aregtech** [comment]
@harshit496 , sounds great.
Thank you!

**Comment by harshit496** [comment]
Hi, @aregtech thanks for assigning this issue although I have hit a roadblock. I use Mac OS for my development work at the moment and this project won't compile with it hence might have to drop this. Do you know of a way that will allow me to keep working on this issue with my current OS?

Also, open to contributing to any of your other open-source projects. Thanks!

**Comment by aregtech** [comment]
Hi @harshit496 
there can be 2 possibilities:
* Install virtual OS using for example [Virtual Box](https://www.virtualbox.org/wiki/Downloads). The codes run under Ubuntu. 
* Fix the build for MacOS. Currently it is using POSIX and Win32 API. If you want to have fun, together we could try to integrate AREG engine for Mac. 

As an IDE i would recommend to use [Visual Studio Code](https://code.visualstudio.com/). It has everything we need.

**Comment by aregtech** [comment]
@harshit496 , or you can use https://github.dev/ to setup your workspace.
It is a nice thing. You don't need anything, just a browser.
I tried it. In the terminal cloned `areg-sdk`, Configured CMake and compiled:
![image](https://user-images.githubusercontent.com/49253642/207713856-190bc679-ead1-476c-a04c-8f7348e2eb50.png)

And these are compiled binaries. Tried couple of them, works perfectly.
![image](https://user-images.githubusercontent.com/49253642/207714243-4c38c8f6-7d6f-4a5a-a77c-e486ab5001c5.png)

**Comment by harshit496** [comment]
Oh yes! Totally forgot about that feature on GitHub. I'll give that a shot. @aregtech

**Comment by harshit496** [comment]
https://github.com/aregtech/areg-sdk/pull/93 created this PR. please take a look this is just a very basic working version.

**Comment by aregtech** [comment]
Thank you @harshit496.
It looks fine.

Let's brainstorm a little bit to find optimal way. Please do not hesitate to make your own suggestion(s).

1. The [CMakeLists.txt](https://github.com/aregtech/areg-sdk/blob/master/CMakeLists.txt#L19) file contains a switcher `BUILD_TESTS`, which by default is OFF -- `option(BUILD_TESTS "Build unit tests")`. This is reserved for unit tests. Another option is ON, so that it compiles examples as well.
2. What do you think if instead of ZIP we create _googletest_ module? This is not a _must_, it is just a suggestion. If you have good reason to use ZIP, I have nothing against.
3. This module can be placed in the new `tests` directory, so that the structure would be
```
areg-sdk
    |
    +--> examples
    |
    +--> framework
    |
    +--> tests
        |
        +--> googletest
        |
        +--> units
```
where the `googletest` is the module and `units` is a subfolder where developers can create tests. 

Please let me know what do you think.

@Ali-Nasrolahi, what do you think?

**Comment by harshit496** [comment]
@aregtech yes it totally makes sense to have a tagged version of the lib stored in the repo in case a user has a network issue. Although would it makes sense to have the googletest dir in a separate dir called third-party which essentially will contain all the third-party libs?

**Comment by Ali-Nasrolahi** [comment]
I, also thinks it's a good idea to have a local module which could be used in case no internet was available. (which by default is off and newest gtest must be used).

As for creating a new directory for third-party libraries, must be decided by @aregtech and project's future needs. But overall it's more convenient to have such hierarchy.

**Comment by aregtech** [comment]
Sorry guys, I was traveling and had no chance to reply.
Actually, the folder `thirdparty` was [already reserved](https://github.com/aregtech/areg-sdk/blob/master/conf/msvc/user.props#L33)  (currently only in MSVC) and it is OK to use.
Initially, i reserved that to use all thirdparty sources relevant only for AREG SDK to track the AREG engine dependencies. Currently it has no dependency, but it is planned to have. But I think we can use for google test as well.

The only thing is that all include paths used in the sources should be relevant to `thidrparty`, because users can easily track. For example, if there is a dependency on `xyz` library and it has subfolder `include/src`, in the sources the include should look like this:
```cpp
#include "xyz/include/src/header.h"
```
Where `xyz` is a subfolder in `thirdparty`.
With this syntax it is visually clear and easy to understand what header is used.

To keep short, we can have this structure in file system:
```
areg-sdk
    |
    +--> examples
    |
    +--> framework
    |
    +--> thirdparty
    |    |
    |    +-->googletest
    |
    +--> tests
        |
        +--> units
```
Let's collect all unit tests in the `units` subfolder, because in the future there might different tests. For example benchmark tests.

@harshit496 , so please feel free to modify add the `googletest` module in AREG SDK located in `thirdparty` folder. Just as a hint you can have a look [here](https://github.com/aregtech/areg-sdk-tools/blob/main/.gitmodules).

**Comment by aregtech** [comment]
Gents,
I've added google test in a [separate branch](https://github.com/aregtech/areg-sdk/tree/feature/60-integrate-google-test).
Let's make all commits here then I'll merge with master. To clone the branch and googletest sources:
```bash
$ git clone --recurse-submodules --branch feature/60-integrate-google-test https://github.com/aregtech/areg-sdk.git ./areg-sdk
```

**Comment by harshit496** [comment]
@aregtech pushed updates. please take a look and let me know if something needs to be changed.

**Comment by aregtech** [comment]
Thank you, @harshit496 .
It looks fine. Made some notes for structure. Please have a look.
