### ISSUE TITLE
Wrong import and export flags of areg library

### ISSUE THREAD

**Issue by aregtech** [aregtech/areg-sdk#61]
**Precondition**
Merged the latest code and cmake changes (issue #28) in the [20220701-candidate](https://github.com/aregtech/areg-sdk/tree/20220701-candidate) branch to make a build.

**Actions**
Make a build using CMake

**Expected**
Compilation with no warnings and errors.

**Result**
When compile examples, see the warning message:
*WARNING: None of preprocessor defines are set. By default sets EXP_AREG_DLL. See GESwitches.h file of AREG API Core*
This may happen only when none of these options is set: **EXP_AREG_DLL**, **EXP_AREG_LIB**, **IMP_AREG_DLL**, **IMP_AREG_LIB**

**Note:** 
1. When compile **areg-sdk frameworklibrary** as shared library (*areg.so* / *areg.dll*) the flag must be **EXP_AREG_DLL**, all other modules must have flag **IMP_AREG_DLL**
2. When compile **areg-sdk frameworklibrary** as static library (*areg.a* / *areg.lib**) the flag must be **EXP_AREG_LIB**, all other modules must have flag **IMP_AREG_LIB**

Only in these cases there will be no warning. Otherwise, there will be a problem compiling for Windows OS, which requires precise import / export flags.

**Comment by aregtech** [comment]
@Ali-Nasrolahi , 
could you please make all you changes directly in [20220701-candidate](https://github.com/aregtech/areg-sdk/tree/20220701-candidate) branch? This branch differs a lot from one, what you forked :)

**Comment by aregtech** [comment]
@biwiki , I tag you. 
Just in case if this would be interesting for you :)

**Comment by Ali-Nasrolahi** [comment]
@aregtech, I've have merged cmake branch with candidate and requested #62.
Build and linking are correctly performed, **however** changes in core causes **Segfault** while trying examples.

**Comment by Ali-Nasrolahi** [comment]
To be more specific almost all examples will failed as such:
```gdb
[#0] 0x7ffff7dba789 → std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)()
[#1] 0x7ffff7efdbef → std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(__str="", this=0x7ffff7fc2718 <Process::_theProcess+88>)
[#2] 0x7ffff7efdbef → std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(__str="", this=0x7ffff7fc2718 <Process::_theProcess+88>)
[#3] 0x7ffff7efdbef → TEString<char>::operator=(src="", this=0x7ffff7fc2718 <Process::_theProcess+88>)
[#4] 0x7ffff7efdbef → String::operator=(src="", this=0x7ffff7fc2718 <Process::_theProcess+88>)
[#5] 0x7ffff7efdbef → Process::_initPaths(this=0x7ffff7fc26c0 <Process::_theProcess>, fullPath=0x55555556e3e0 "/areg-sdk/product/build/g++/Linux-x86_64-Release/bin/03_file")
[#6] 0x7ffff7f0b4ae → Process::initilize(this=0x7ffff7fc26c0 <Process::_theProcess>)
[#7] 0x7ffff7f7224d → Process::getInstance()
[#8] 0x7ffff7f7224d → TraceManager::TraceManager(this=0x7ffff7fc8260 <TraceManager::getInstance()::_theTraceManager>)
[#9] 0x7ffff7f72354 → TraceManager::getInstance()

```

**Comment by aregtech** [comment]
Hi @Ali-Nasrolahi,
OK, I'll have a look.
Which example you started?

**Comment by Ali-Nasrolahi** [comment]
Hello, @aregtech.
This is from third examples (03_file), but I believe first four examples has same issue as well.

**Comment by aregtech** [comment]
OK, @Ali-Nasrolahi. Thank you, i'll check and let you know.

**Comment by aregtech** [comment]
The quick fix to have file extension. The binary file does not have extension.

**Comment by aregtech** [comment]
@Ali-Nasrolahi 
I've fixed the problem with segmentation fault.
Made tests with examples 01 .. 11
Now all look fine.
Please let me know if you see anything abnormal.

Thank you fixing this issue with warnings. The changes are in the branch.
Closing ticke.

**Comment by Ali-Nasrolahi** [comment]
@aregtech, great! :)
