### ISSUE TITLE
Copy config files after compilation

### ISSUE THREAD

**Issue by aregtech** [aregtech/areg-sdk#74]
**Motivation**
1. After compilation, the developer should be able to start any project without additional effort. At this moment, to start IPC project or to configure logging, after compilation with `cmake`, the developer needs manually create `config` subdirectory and copy `log.init` and `router.init` files in the folder of binaries. For example, compiling with `msvc` and `make` automatically do this action.
2. `make` under `Linux` compiles and creates binaries with extension `.out` and `msvc` compiles binaries with extension `.exe`. 
3. Both, `make` and `msvc` compile with incremental build, which is much faster and does not require to recompile all projects.

**What to do**
1. After compilation of binaries with `cmake`, create `config` subfolder in the binary output folder `bin` (i.e. in `bin/config`) if it is not existing, and copy files [log.init](https://github.com/aregtech/areg-sdk/blob/master/framework/areg/resources/log.init) used by logging and [router.init](https://github.com/aregtech/areg-sdk/blob/master/framework/areg/resources/router.init) used for IPC.
2. When compile under Linux, add `.out` extension to executable binaries, i.e. the `mcrouter` is `mcrouter.out`. No need to make this change for Windows, because the compiler automatically adds extension `.exe`.
3. Support incremental build with `cmake` at least for `Debug` configuration, so that there will be no need to rebuild all projects after each small change.

**Comment by aregtech** [comment]
Hi @Ali-Nasrolahi,
I'll be very thankful if you extend cmake support: copy config files, change binary extensions and make build incremental.

FYI, probably it helps. In the [Makefile](https://github.com/aregtech/areg-sdk/blob/master/framework/areg/Makefile) of areg project, written by @biwiki, at the end there are scripts:
```make
@mkdir -p $(AREG_OUTPUT_BIN)/config
@cp $(areg_BASE)/resources/log.init $(areg_BASE)/resources/router.init $(AREG_OUTPUT_BIN)/config/ 
```

Many thanks in advance!

**Comment by Ali-Nasrolahi** [comment]
Hello @aregtech,
I understood the first two TODOs , however the third one (incremental build) is little bit vague to me.
Could you explain/reference a more detailed description?

Thanks a lot!

**Comment by aregtech** [comment]
The [incremental compiler](https://en.wikipedia.org/wiki/Incremental_compiler)
>  Quite naturally, whereas ordinary compilers make a so-called clean build, that is, (re)build all program modules, **an incremental compiler recompiles only modified portions of a program**.

It means that the compiler checks the timestamp of source and compiled file, and compiles only if source has been changed. It also checks the dependencies, i.e. if file `a.hpp` is included in `a.cpp` and `b.cpp`, and not included in `c.cpp`, the modification of `a.hpp` will cause re-build of `a.cpp` and `b.cpp`, but not `c.cpp`. 
The expectation is that when in areg framework, compiled as shared library, make modifications not related with examples, the examples are not compiled. Or if make changes only in an example project, it will not require compilation of all entire codes, but only that particular project.

I know how to enable / disable in MSVS, but don't know how to do that in CMake. Might be possible, it is a compiler specific option.

Maybe @biwiki helps / gives a hint when finds a little time 🙂 He implemented that for `make` and it works.

**Comment by Ali-Nasrolahi** [comment]
Thanks, I will look into it.
